name: PR Reviewer

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  packages: read

jobs:
  review:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/vijayabhaskar78/pr-reviewer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --workdir /app  # ðŸ‘ˆ Ensures it runs inside /app even before step

    steps:
      - name: Run PR Reviewer
        run: python src/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
